spring:
 datasource:
    url: jdbc:oracle:thin:@provecrew_high?TNS_ADMIN=C:/opt/OracleCloudWallet/VFX/
    username: provecrew
    password: Oracle12345678
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 200000
      max-lifetime: 240000
      pool-name: oraPool
