spring:
 datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 200000
      max-lifetime: 240000
      pool-name: oraPool